name: CI/CD Deployment

on: 
  push:
    branches: [master]
jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: setup node.js
        uses: actions/setup-node@v2-beta
        with:
          version: 12
      - name: Github Actions of Yarn
        uses: Borales/actions-yarn@2.1.0
        with:
          cmd: install
          
      - name: Creating build
        run: CL=false yarn build
        
      - name: install surge
        run: npm install -g surge
        
      - name: depolying on surge
        run: surge ./build http://task-tracker-asadullahkhan.surge.sh  --token ${{secrets.SURGE_TOKEN}}
          
